name: Auto Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-2022

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v5

      - uses: nuget/setup-nuget@v3

      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            buildprops:
              - 'Directory.Build.props'

      - name: NuGet restore
        run: nuget restore OpenHardwareMonitor.sln

      - name: Build
        run: msbuild OpenHardwareMonitor.sln -p:Configuration=Release -p:Platform="Any CPU" -m

      - name: Publish build
        uses: actions/upload-artifact@v5
        with:
          name: OpenHardwareMonitor
          path: OpenHardwareMonitor/bin

      - name: Publish Lib build
        uses: actions/upload-artifact@v5
        with:
          name: OpenHardwareMonitorLib
          path: OpenHardwareMonitorLib/bin